name: ttrp-env
channels:
  - conda-forge
dependencies:
  - geopandas
  - rasterio
  - statsmodels
  - seaborn
  - jupyter
  - marimo
  - mystmd
  - pystac
  - pystac-client
  - boto3
  - pip
  - pip:
      - jupyterlab_myst
